Testing
YunoHost-Apps/mautrix_whatsapp_ynh pull request #26
Opened 2021-06-17 21:50 UTC by Gredin67

## Problem
- *Description of why you made this PR*

## Solution
- *And how do you fix that problem*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/APP_ynh%20PR-NUM-%20(USERNAME)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/APP_ynh%20PR-NUM-%20(USERNAME)/)

2021-06-21 14:36 UTC, Gredin67 commented
!testme

2021-06-21 14:41 UTC, oufmilo commented
!testme

2021-06-21 18:48 UTC, oufmilo commented
I's a manifest problem but i don't understand ..

2021-06-22 09:03 UTC, Gredin67 commented
I  really don't get what is happening here with process check https://ci-apps-dev.yunohost.org/ci/job/2177
``&bot_is_synapse_admin=package_checker``
@alexAubin

2021-06-22 09:26 UTC, Gredin67 commented
for the upgrade failing, we obviously need to remove more files before upgrading, or to git pull in some folder https://github.com/tulir/mautrix-whatsapp/issues/317
The fresh install failing because of missing config file. I tried to add a sleep time to wait for the config file to be generated. Otherwise we have to understand why ynh_add_config does not generate the file properly

2021-06-22 16:57 UTC, Gredin67 commented
!testme

2021-06-23 22:45 UTC, Gredin67 commented
!testme

2021-06-24 05:36 UTC, Gredin67 commented
!testme

2021-06-24 13:15 UTC, Gredin67 commented
!testme

2021-06-24 18:57 UTC, Gredin67 commented
!testme

2021-06-27 14:45 UTC, Gredin67 commented
!testme

2021-06-27 20:33 UTC, Gredin67 commented
!testme

2021-06-27 20:54 UTC, Gredin67 commented
@tituspijean could you have a look at this PR, I tried maaany things but the ``go build`` does not work with the upgraded sources.
The standard procedure is to do ``git pull`` rather than downloading new sources. And the maintainer thinks it could be related. https://github.com/tulir/mautrix-whatsapp/issues/317

I am thinking of not using ``ynh_setup_sources`` anymore and rather doing a ``git checkout v0.1.7`` to see what it gives..

2021-06-27 21:55 UTC, Gredin67 commented
!testme

2021-06-28 04:38 UTC, oufmilo requested changes
;;; Upgrade options
	; commit=636be2f9f900e578d9aa26ee887dcec2ef8d4e71
		name=0.1.7

2021-06-28 05:05 UTC, oufmilo requested changes

2021-06-28 05:05 UTC, oufmilo commented on check_process
> -;;; Upgrade options
;;; Upgrade options
	; commit=636be2f9f900e578d9aa26ee887dcec2ef8d4e71
		name=0.1.7

2021-06-28 05:10 UTC, oufmilo requested changes
check_process update

2021-06-28 05:10 UTC, oufmilo commented on check_process
> -	; commit=CommitHash
; commit=636be2f9f900e578d9aa26ee887dcec2ef8d4e71

2021-06-28 05:10 UTC, oufmilo commented on check_process
> -;;; Upgrade options
;;; Upgrade options

2021-06-28 05:10 UTC, oufmilo commented on check_process
> -		#name=Name and date of the commit.
name=0.1.7

2021-06-28 06:31 UTC, oufmilo commented
!testme

2021-06-28 20:07 UTC, merged